version: "3"

networks:
  default:
    external:
      name: external

services:
  bsc_mainnet:
    image: zinnionlcc/bsc_geth
    container_name: bsc_mainnet
    hostname: bsc_mainnet
    restart: unless-stopped
    ports:
      - "8575:8575"
      - "8547:8547" # Websocket
      - "8576:8576"
      - "8577:8577"
      - "30311:30311/udp"
      - "30311:30311"
    volumes:
      - ./data/mainnet/:/root/.ethereum/
      - ./config/mainnet/config.toml:/config.toml
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - bsc
      - --nousb
      - --syncmode=full
      - --nousb
      - --cache=8192
      - --maxpeers=100
      - --pprof
      - --rpc
      - --rpcaddr
      - "0.0.0.0"
      - --rpcvhosts
      - "*"
      - --rpccorsdomain
      - "*"
      - --ws
      - --wsaddr
      - "0.0.0.0"
      - --wsorigins
      - "*"
      - --wsapi
      - eth,net,web3
      - --wsport
      - "8547"
      - --datadir
      - "/root/.ethereum/"
      - --config
      - /config.toml
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  bsc_testnet:
    image: zinnionlcc/bsc_geth
    container_name: bsc_testnet
    hostname: bsc_testnet
    restart: unless-stopped
    ports:
      - "7575:8575"
      - "7547:8547" # Websocket
      - "7576:8576"
      - "7577:8577"
      - "20311:30311/udp"
      - "20311:30311"
    volumes:
      - ./data/testnet/:/root/.ethereum/
      - ./config/testnet/config.toml:/config.toml
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - bsc
      - --nousb
      - --syncmode=full
      - --nousb
      - --cache=8192
      - --maxpeers=100
      - --pprof
      - --rpc
      - --rpcaddr
      - "0.0.0.0"
      - --rpcvhosts
      - "*"
      - --rpccorsdomain
      - "*"
      - --ws
      - --wsaddr
      - "0.0.0.0"
      - --wsorigins
      - "*"
      - --wsapi
      - eth,net,web3
      - --wsport
      - "8547"
      - --datadir
      - "/root/.ethereum/"
      - --config
      - /config.toml
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
      