version: "3"

networks:
  monitor-net:
    driver: bridge

services:
  bsc_geth:
    image: zinnionlcc/bsc_geth
    container_name: bsc_geth
    hostname: bsc_geth
    restart: unless-stopped
    ports:
      - "8547:8547" # Websocket
      - "8575:8575"
      - "8576:8576"
      - "8577:8577"
      - "30311:30311/udp"
      - "30311:30311"
    volumes:
      - ./goethereum:/var/lib/goethereum
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - bsc
      - --nousb
      - --syncmode=fast
      - --nousb
      - --cache=8192
      - --maxpeers=100
      - --metrics
      - --pprof
      - --rpc
      - --rpcport=8575
      - --rpcaddr=0.0.0.0
      - --ws
      - --wsaddr=0.0.0.0
      - --wsorigins="*"
      - --wsapi
      - eth,net,web3
      - --wsport=8547
      - --datadir
      - "/var/lib/goethereum"
      - --config 
      - /config.toml
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"